# Generated by Django 4.0.4 on 2022-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('isdel', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('create_time', models.CharField(max_length=20)),
                ('update_time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
